[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
keikibook = "5zu8sjZbddeGZxptq97vEyiB4w7cKufMJhmY5MSn4a47"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
#{localnet, devnet, testnet, mainnet}
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
